[package]
name = "kmod-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
object = "0.30.0"
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
